### PR TITLE
Add support for autoplay and loop attributes

### PR DESCRIPTION
**Pull request by grrowl**
Now I can do this:

```md
{{% video src="future-video" autoplay="true" loop="true" %}}
```

having any value defined for "autoplay" or "loop" will add the properties to the `video` element

### CODE REVIEW

**Comment by grrowl** [comment]
Although just realised these are boolean attributes — so this should be an `if` instead of a `when` — ~please stand by~

edit: this is done, thanks!

**Comment by grrowl** [comment]
Added `muted` too, since I happened to see this on [the MDN docs for `video`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Attributes):

> In some browsers (e.g. Chrome 70.0) autoplay doesn't work if no muted attribute is present.

There might be a better way handle simple boolean attributes in code (with a Map or something) but I'm a little bit new to hugo shortcodes, but happy to take suggestion. Thanks!

**Comment by martignoni** [comment]
This is not forgotten, but I didn't have the time to integrate it yet :-/

**Review by martignoni — COMMENTED** [review]
Thank you for this.

If one has `autoplay="false"` (or any other string, including empty one `""`), the `autoplay` attribute is printed anyway. Same thing with `loop` and `muted`.

You should add some test, e.g.
```go
{{ if eq (.Get "autoplay") "true" }}autoplay {{ end }}
```
Please move too the trailing space inside the test, so that there's no double space in the source (see example above).

**Comment by grrowl** [comment]
Great feedback, thanks! Updated the PR

**Review by martignoni — APPROVED** [review]
OK :-)

**Pull request merged**
